### ISSUE TITLE
推荐飞利浦空气炸锅

### ISSUE THREAD

**Issue by allen0125** [happypeter/food#1]
菜谱，有飞利浦空气炸锅的APP，挑选合适自己的就可以拉，肯定能选出14个菜满足两周午饭不重复吧。

**Comment by guoruibiao** [comment]
感觉除了既定的方案，是不是还得从**个人**这块下手，每个人代谢可能不会相同，根据代谢水平去定制方案，或许减肥更快呐。

**Comment by happypeter** [comment]
Cool advices

**Comment by happypeter** [comment]
最近发现还是抽不出足够的时间自己做饭，所以没有购买这个锅。
