### ISSUE TITLE
感觉有点缘木求鱼

### ISSUE THREAD

**Issue by Terry-Qin** [happypeter/food#3]
既然是为了减肥，不应该是多花点心思在怎么坚持锻炼上吗，要是花心思研究怎么吃会误入歧途吧。
另外，外卖是能不吃就不吃了。

**Comment by happypeter** [comment]
研究的越好吃，肯定吃的越多 :dancer:

**Comment by luckyyang** [comment]
锻炼主要是为了增加身体的力量和免疫力，如果减肥主要还是靠饮食

**Comment by happypeter** [comment]
YES
